jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -V || python3 -V
          ls -R
      - env: { PYTHONPATH: ${{ github.workspace }} }
        run: |
          python -m unittest discover -s tests -t . -p "test_*.py" -v \
          || python3 -m unittest discover -s tests -t . -p "test_*.py" -v
