name: Python unit tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Show environment
        run: |
          python -V || python3 -V
          ls -R
      - name: Run unittest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m unittest discover -s tests -t . -p "test_*.py" -v \
          || python3 -m unittest discover -s tests -t . -p "test_*.py" -v
